"""designation

Revision ID: 415d411ff9fa
Revises: 733493a170c1
Create Date: 2024-04-19 09:59:39.802695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '415d411ff9fa'
down_revision: Union[str, None] = '733493a170c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'designation',
               existing_type=postgresql.ENUM('ADMIN', 'DEVICE_MANAGER', 'STAFF', 'VIEWER', name='designation'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'designation',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'DEVICE_MANAGER', 'STAFF', 'VIEWER', name='designation'),
               existing_nullable=True)
    # ### end Alembic commands ###
