"""empty message

Revision ID: 4228f0c16a2d
Revises: 041e4bdfa21b
Create Date: 2024-04-11 21:55:55.348643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4228f0c16a2d'
down_revision: Union[str, None] = '041e4bdfa21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'deleted')
    op.drop_column('device', 'deleted_at')
    op.drop_column('device', 'deleted')
    # ### end Alembic commands ###
