"""updated

Revision ID: 4644d83fc16c
Revises: 4228f0c16a2d
Create Date: 2024-04-11 23:46:56.007562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4644d83fc16c'
down_revision: Union[str, None] = '4228f0c16a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('device', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
