"""non deffer columns

Revision ID: 58e7d615d5e2
Revises: fab67ac9c2c7
Create Date: 2024-04-18 23:07:48.821854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e7d615d5e2'
down_revision: Union[str, None] = 'fab67ac9c2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
