"""designation

Revision ID: 733493a170c1
Revises: 58e7d615d5e2
Create Date: 2024-04-19 09:57:43.577106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '733493a170c1'
down_revision: Union[str, None] = '58e7d615d5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'designation',
               existing_type=postgresql.ENUM('ADMIN', 'DEVICE_MANAGER', 'STAFF', 'VIEWER', name='designation'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'designation',
               existing_type=postgresql.ENUM('ADMIN', 'DEVICE_MANAGER', 'STAFF', 'VIEWER', name='designation'),
               nullable=False)
    # ### end Alembic commands ###
