"""added temp password

Revision ID: 8fe01131a324
Revises: 9877f76c6d40
Create Date: 2024-04-18 14:18:36.356419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe01131a324'
down_revision: Union[str, None] = '9877f76c6d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temp_password', sa.String(), nullable=True))
    op.add_column('user', sa.Column('temp_password_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temp_password_created_at')
    op.drop_column('user', 'temp_password')
    # ### end Alembic commands ###
