"""designation

Revision ID: 996539bf68d9
Revises: 415d411ff9fa
Create Date: 2024-04-19 10:02:39.212239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996539bf68d9'
down_revision: Union[str, None] = '415d411ff9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'DEVICE_MANAGER', 'STAFF', 'VIEWER', name='roletype'),
               existing_nullable=False)
    op.alter_column('user', 'designation',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MANAGER', 'DEVELOPER', 'HR', 'IT_SUPPORT', 'CEO', 'VIEWER', name='designation'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'designation',
               existing_type=sa.Enum('MANAGER', 'DEVELOPER', 'HR', 'IT_SUPPORT', 'CEO', 'VIEWER', name='designation'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('role', 'name',
               existing_type=sa.Enum('ADMIN', 'DEVICE_MANAGER', 'STAFF', 'VIEWER', name='roletype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
