"""device request status

Revision ID: f333a6e97b2d
Revises: 54cc867f79ff
Create Date: 2024-04-26 09:13:51.112432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f333a6e97b2d'
down_revision: Union[str, None] = '54cc867f79ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_request_records', sa.Column('request_status', sa.Enum('pending', 'accepted', 'rejected', name='requeststatus'), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_request_records', 'request_status')
    # ### end Alembic commands ###
